name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Install Sonarqube
      run: dotnet tool update dotnet-sonarscanner
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet-sonarscanner begin /k:"cabadam_otel-http" /o:"cabadam" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
        dotnet build --no-restore
        dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    - name: Test
      run: dotnet test --no-build --verbosity normal
